version: "3.8"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=sqlite:///./smaport.db
      - CORS_ORIGINS=http://localhost:8501
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    command: bash -c "pip install -r /app/requirements.txt && streamlit run /app/app.py --server.port 8501 --server.address 0.0.0.0"
